/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */
import { chessbase, chessTalk, ericRosen, gothamChess } from "../../assets";


export const videos = [
  {
    _id: "Wo5dMEP_BbA",
    title: "Basic Opening Chess Trap | Budapest Gambit",
    videoLength: "10:29",
    youtubeID: "xfa3PXq2-sU",
    thumbnail: "http://i3.ytimg.com/vi/xfa3PXq2-sU/hqdefault.jpg",
    channelName: "Chessbase India",
    channelImg: chessbase,
    category: "Gambit",
    description:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
  },
  {
    _id: "Wo5dMEP_BbP",
    title: "Learn the Stonewall Defense & Attack | 10-Minute Chess Openings",
    videoLength: "10:29",
    youtubeID: "4_brAnORWGw",
    thumbnail: "http://i3.ytimg.com/vi/4_brAnORWGw/hqdefault.jpg",
    channelName: "GothamChess",
    channelImg: gothamChess,
    category: "Opening",
    description:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
  },
  {
    _id: "Wo5dMEP_BbQ",
    title: "Play the Sicilian Defense Opening like Beth Harmon",
    videoLength: "10:29",
    youtubeID: "65VWIFlc4C4",
    thumbnail: "http://i3.ytimg.com/vi/65VWIFlc4C4/hqdefault.jpg",
    channelName: "GothamChess",
    channelImg: gothamChess,
    category: "Opening",
    description:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
  },
  {
    _id: "Wo5dMEP_BbD",
    title: "Basic Opening Chess Trap | Cochrane Gambit in the Petroff",
    videoLength: "10:29",
    youtubeID: "tqgoxsfHoK0",
    thumbnail: "http://i3.ytimg.com/vi/tqgoxsfHoK0/hqdefault.jpg",
    channelName: "Chessbase India",
    channelImg: chessbase,
    category: "Gambit",
    description:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
  },
  {
    _id: "Wo5dMEP_BbE",
    title: "Bishop Endgames",
    videoLength: "10:29",
    youtubeID: "iznr0F-zY-4",
    thumbnail: "http://i3.ytimg.com/vi/iznr0F-zY-4/hqdefault.jpg",
    channelName: "Chessbase India",
    channelImg: chessbase,
    category: "Endgame",
    description:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
  },
  {
    _id: "Wo5dMEP_BbF",
    title: "Parimarjan Negi's immortal against Svetushkin",
    videoLength: "10:29",
    youtubeID: "1ffXBrZnbyw",
    thumbnail: "http://i3.ytimg.com/vi/1ffXBrZnbyw/hqdefault.jpg",
    channelName: "Chessbase India",
    channelImg: chessbase,
    category: "Classic",
    description:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
  },
  {
    _id: "Wo5dMEP_BbG",
    title: "Garry Kasparov vs Vishy Anand, 1995 | The Evans Gambit",
    videoLength: "10:29",
    youtubeID: "-r3aclHSNsw",
    thumbnail: "http://i3.ytimg.com/vi/-r3aclHSNsw/hqdefault.jpg",
    channelName: "Chessbase India",
    channelImg: chessbase,
    category: "Classic",
    description:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
  },
  {
    _id: "Wo5dMEP_BbM",
    title: "Queen vs Pawn Endgame",
    videoLength: "10:29",
    youtubeID: "2q-TjB6YYRI",
    thumbnail: "http://i3.ytimg.com/vi/2q-TjB6YYRI/hqdefault.jpg",
    channelName: "GothamChess",
    channelImg: gothamChess,
    category: "Endgame",
    description:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
  },
  {
    _id: "Wo5dMEP_BbN",
    title: "Rook & Pawn Endgame",
    videoLength: "10:29",
    youtubeID: "JMZJ9P2Hnq0",
    thumbnail: "http://i3.ytimg.com/vi/JMZJ9P2Hnq0/hqdefault.jpg",
    channelName: "GothamChess",
    channelImg: gothamChess,
    category: "Endgame",
    description:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
  },
  {
    _id: "Wo5dMEP_BbJ",
    title: "Rook vs Pawns Endgame",
    videoLength: "10:29",
    youtubeID: "mZquhq8Nz94",
    thumbnail: "http://i3.ytimg.com/vi/mZquhq8Nz94/hqdefault.jpg",
    channelName: "Chessbase India",
    channelImg: chessbase,
    category: "Endgame",
    description:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
  },
  {
    _id: "Wo5dMEP_BbK",
    title: "Rook + Bishop vs Rook II + Bishop & Knight mate",
    videoLength: "10:29",
    youtubeID: "yzasukqyE1I",
    thumbnail: "http://i3.ytimg.com/vi/yzasukqyE1I/hqdefault.jpg",
    channelName: "Chessbase India",
    channelImg: chessbase,
    category: "Endgame",
    description:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
  },
  {
    _id: "Wo5dMEP_BbL",
    title: "King & Pawn Endgame",
    videoLength: "10:29",
    youtubeID: "mCsc24k-Q8M",
    thumbnail: "http://i3.ytimg.com/vi/mCsc24k-Q8M/hqdefault.jpg",
    channelName: "GothamChess",
    channelImg: gothamChess,
    category: "Endgame",
    description:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
  },
  {
    _id: "Wo5dMEP_BbH",
    title: "Kramnik's immortal against Gelfand, 1996",
    videoLength: "10:29",
    youtubeID: "Gjoxxg0c4MA",
    thumbnail: "http://i3.ytimg.com/vi/Gjoxxg0c4MA/hqdefault.jpg",
    channelName: "Chessbase India",
    channelImg: chessbase,
    category: "Classic",
    description:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
  },
  {
    _id: "Wo5dMEP_BbI",
    title: "Vidit Gujrathi's immortal against Vladimir Kramnik",
    videoLength: "10:29",
    youtubeID: "OTRnnUPcZCE",
    thumbnail: "http://i3.ytimg.com/vi/OTRnnUPcZCE/hqdefault.jpg",
    channelName: "Chessbase India",
    channelImg: chessbase,
    category: "Classic",
    description:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
  },
  {
    _id: "Wo5dMEP_BbO",
    title: "Learn the Caro-Kann Defense | 10-Minute Chess Openings",
    videoLength: "10:29",
    youtubeID: "rmbU97iftC8",
    thumbnail: "http://i3.ytimg.com/vi/rmbU97iftC8/hqdefault.jpg",
    channelName: "GothamChess",
    channelImg: gothamChess,
    category: "Opening",
    description:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
  },
  {
    _id: "Wo5dMEP_BbB",
    title: "Basic Opening Chess Trap | Sicilian Defence | Morra Gambit",
    videoLength: "10:29",
    youtubeID: "geJfIY2DhcA",
    thumbnail: "http://i3.ytimg.com/vi/geJfIY2DhcA/hqdefault.jpg",
    channelName: "Chessbase India",
    channelImg: chessbase,
    category: "Gambit",
    description:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
  },
  {
    _id: "Wo5dMEP_BbC",
    title: "Basic Opening Chess Trap | Danish Gambit | Free Queen or not?",
    videoLength: "10:29",
    youtubeID: "5SYR4oThgh8",
    thumbnail: "http://i3.ytimg.com/vi/5SYR4oThgh8/hqdefault.jpg",
    channelName: "Chessbase India",
    channelImg: chessbase,
    category: "Gambit",
    description:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
  },
  {
    _id: "Wo5dMEP_BbR",
    title: "WIN IN 8 MOVES | The Fried Liver Attack Opening",
    videoLength: "10:29",
    youtubeID: "va0s92praEM",
    thumbnail: "http://i3.ytimg.com/vi/hLFSufXxtuI/hqdefault.jpg",
    channelName: "GothamChess",
    channelImg: gothamChess,
    category: "Opening",
    description:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
  },
  {
    _id: "Wo5dMEP_BbS",
    title: "Trapping a Grandmaster in 7 Moves | Stafford Gambit",
    videoLength: "10:29",
    youtubeID: "ztOW6VZlrxQ",
    thumbnail: "http://i3.ytimg.com/vi/ztOW6VZlrxQ/hqdefault.jpg",
    channelName: "Eric Rosen",
    channelImg: ericRosen,
    category: "Gambit",
    description:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
  },
  {
    _id: "Wo5dMEP_BbT",
    title: "Mikhail Tal's Greatest Queen Sacrifice! Best Chess Games",
    videoLength: "10:29",
    youtubeID: "vBhnjG-sIRU",
    thumbnail: "http://i3.ytimg.com/vi/vBhnjG-sIRU/hqdefault.jpg",
    channelName: "Chess Talk",
    channelImg: chessTalk,
    category: "Classic",
    description:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
  },
  {
    _id: "Wo5dMEP_BbU",
    title: "MIND-BLOWING GAME || Magnus Carlsen vs Ian Nepomniachtchi || FIDE World Chess Championship 2021",
    videoLength: "10:29",
    youtubeID: "RtKPc-e9tUw",
    thumbnail: "http://i3.ytimg.com/vi/RtKPc-e9tUw/hqdefault.jpg",
    channelName: "Chess Talk",
    channelImg: chessTalk,
    category: "Classic",
    description:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
  },
  {
    _id: "Wo5dMEP_BbV",
    title: "Bobby Fischer’s Best Chess Game Ever! | Fischer vs R. Byrne - US, 1963 | The Brilliancy Prize",
    videoLength: "10:29",
    youtubeID: "EMDJebpc4oQ",
    thumbnail: "http://i3.ytimg.com/vi/EMDJebpc4oQ/hqdefault.jpg",
    channelName: "Chess Talk",
    channelImg: chessTalk,
    category: "Classic",
    description:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
  },
];
